name: 'Save SiteGround Speed Optimizer config to Git'
description: 'A GitHub Action that saves SiteGround Speed Optimizer configuration to versioned JSON file in your repository.'
author: 'pronamic'

branding:
  icon: 'download-cloud'
  color: 'orange'

inputs:
  ssh_host:
    description: ''
    required: true
  ssh_user:
    description: ''
    required: true
  ssh_key:
    description: ''
    required: true
  wp_cli_path:
    description: ''
    required: false
  wp_cli_url:
    description: ''
    required: false
  file:
    description: ''
    required: false
    default: 'sg-speed-optimizer-settings.json'

runs:
  using: 'composite'
  steps:
    - name: Create SSH directory
      run: |
        mkdir -p ~/.ssh
      shell: bash

    - name: Add SSH private key and set permissions
      run: |
        echo "${{ inputs.ssh_key }}" > ~/.ssh/siteground
        chmod 600 ~/.ssh/siteground
      shell: bash

    - name: Add SiteGround host key to known_hosts
      run: |
        ssh-keyscan -H -p 18765 ${{ inputs.ssh_host }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
      shell: bash

    - name: Create SSH config for SiteGround alias
      run: |
        echo "Host siteground
          HostName ${{ inputs.ssh_host }}
          User ${{ inputs.ssh_user }}
          Port 18765
          IdentityFile ~/.ssh/siteground
          IdentitiesOnly yes
          StrictHostKeyChecking yes" > ~/.ssh/config
        chmod 600 ~/.ssh/config # Good practice for config file permissions
      shell: bash

    - id: sg-settings-export
      name: Export SiteGround Speed Optimizer settings
      run: |
        result=$(ssh siteground "wp sg settings export --path=${{ inputs.wp_cli_path }}")
        echo "$result"
        {
          echo "settings<<EOF"
          echo "$result"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run save script
      run: php ${{ github.action_path }}/save.php --file="${{ inputs.file }}" --settings="${{ steps.sg-settings-export.outputs.settings }}"
      shell: bash
