name: 'Saved SiteGround Speed Optimizer config to Git'
description: 'A GitHub Action that saves SiteGround Speed Optimizer configuration to versioned JSON file in your repository.'
author: 'pronamic'

branding:
  icon: 'download-cloud'
  color: 'orange'

inputs:
  ssh_host:
    description: ''
    required: true
  ssh_user:
    description: ''
    required: true
  ssh_key:
    description: ''
    required: true
  wp_cli_path:
    description: ''
    required: false
  wp_cli_url:
    description: ''
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup SSH directory
      run: |
        mkdir -p ~/.ssh

    - name: Add SSH key for SiteGround
      run: |
        echo "${{ inputs.ssh_key }}" > ~/.ssh/siteground
        chmod 600 ~/.ssh/siteground

    - name: Setup SSH config for SiteGround
      run: |
        echo "Host siteground
          HostName ${{ inputs.ssh_host }}
          User ${{ inputs.ssh_user }}
          IdentityFile ~/.ssh/siteground
          IdentitiesOnly yes
          StrictHostKeyChecking yes" > ~/.ssh/config

    - name: Run command on SiteGround
      run: |
        ssh siteground 'echo "✅ Verbonden met SiteGround"'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run save script
      run: php ${{ github.action_path }}/save.php
      shell: bash
      env:
        INPUT_SSH_HOST: ${{ inputs.ssh_host }}
        INPUT_SSH_USER: ${{ inputs.ssh_user }}
